GET http://localhost:3000/campaigns/ch5bmo906e6il5u3pp3g

###

POST http://localhost:3000/campaigns

{
    "Name" : "LeandroL da sila",     
	"Content" : "bodyyyy",
	"emails":  ["Leandaaro222@hotmail.com"]
}

###

DELETE http://localhost:3000/campaigns/delete/ch5bmo906e6il5u3pp3g
