GET http://localhost:3000/campaigns/cgrh0b906e6hb97ildrg

###


###

POST http://localhost:3000/campaigns

{
    "Name" : "Leandro second",     
	"Content" : "boooodie",
	"emails":  ["Leandro2@hotmail.com"]
}
